[bans]
multiple-versions = "warn"
wildcards = "allow"
highlight = "all"
workspace-default-features = "allow"
external-default-features = "allow"
allow = []
deny = []
skip = [
    { name = "getrandom" },
    { name = "regex-automata" },
    { name = "regex-syntax" },
    { name = "wasi" },
    { name = "windows-sys" },
    { name = "windows-targets" },
    { name = "windows_aarch64_gnullvm" },
    { name = "windows_aarch64_msvc" },
    { name = "windows_i686_gnu" },
    { name = "windows_i686_gnullvm" },
    { name = "windows_i686_msvc" },
    { name = "windows_x86_64_gnu" },
    { name = "windows_x86_64_gnullvm" },
    { name = "windows_x86_64_msvc" },
]
skip-tree = []

[advisories]
db-path = "~/.cargo/advisory-db"
db-urls = ["https://github.com/rustsec/advisory-db"]
unmaintained = "all"
yanked = "warn"
ignore = []

[licenses]
allow = ["MIT", "Apache-2.0", "BSD-3-Clause", "GPL-3.0", "Unicode-3.0", "MPL-2.0", "0BSD", "BSL-1.0", "LGPL-2.1", "Unlicense", "Zlib", "ISC", "CDLA-Permissive-2.0"]
exceptions = [
    { allow = ["Apache-2.0 WITH LLVM-exception"], name = "linux-raw-sys" },
    { allow = ["Apache-2.0 WITH LLVM-exception"], name = "rustix" },
    { allow = ["Apache-2.0 WITH LLVM-exception"], name = "wasi" },
    { allow = ["Apache-2.0 WITH LLVM-exception"], name = "wit-bindgen-rt" },
]
confidence-threshold = 0.8

[sources]
unknown-registry = "warn"
unknown-git = "warn"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = []